# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: affe9ab06080adedd1224098c0d4c344a84723cdea5733eac3b24a89857fd3ce5a8a484671c74900be202af44a34e8f30242390945dc53cda6c81a3ed5009105

test:
  secret_key_base: 644d4928b110c872232bee137ef4e334720003926534bfcde66244e8c5c82cfb7dbdeb63040b72baa118d357f5b8af7ae04bfcda75496cbc4b3df82bd31c936f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
